language: node_js

node_js:
  - '14'

sudo: false

services:
  - mongodb
  - docker

# Add your branch here to have it tested and deployed
branches:
  only:
  - master

before_install:
  # Configure Git
  - git config --global user.email "travis-ci@legalthings.net"
  - git config --global user.name "Travis CI"

  # Get all tags of git repo
  - git fetch origin 'refs/tags/*:refs/tags/*'

script:
  - npm run build
  - npm run test:all
